Dmytro Voytanovich: v2
kodolabs/vue-playground pull request #3
Opened 2023-02-12 19:15 UTC by voutanon

2023-02-13 10:05 UTC, jurgens requested changes

2023-02-13 10:05 UTC, jurgens commented on src/App.vue
> +      getVenues: 'venue/getVenues'
можно и так конечно, но (по крайней мере в нашем примере) лучше это делать непосредственно там где эти данные требуются

2023-02-13 10:05 UTC, jurgens commented on src/components/forms/formReview.vue
> +<template>
тут ты совершаешь одну распространенную ошибку - при попытке структурировать компоненты приложения, что само по себе хорошо, ты делаешь неправильный выбор в пользу структурирования по типу (forms), тогда как более правильно - по функционалу, то есть на первом месте лучше ставить название модуля (reviews), а дальше либо добавлять какую-либо суб-структуру, либо не делать этого, пока не возникнет необходимость.

на мой взгляд, хорошим названием тут будет components/venues/newReview.vue

2023-02-13 10:05 UTC, jurgens commented on src/components/forms/formReview.vue
> +    <form @submit.prevent="createReview()">
не совсем верное название
тут нужно либо использовать абстрактное название типа formSubmitHandler
либо уже точную бизнес логику, а она не в создании ревью, а в сохранении формы для дальнейшего просмотра (то есть можно назвать это storeReviewForPreview)

2023-02-13 10:05 UTC, jurgens commented on src/components/forms/formReview.vue
> +      this.setReview({ text: this.text, rating: this.rating })
потерял id заведения, к которому относится отзыв
это довольно критическая ошибка

2023-02-13 10:05 UTC, jurgens commented on src/components/forms/formReview.vue
> +      this.$router.push({name: "previewWatch", params: { id: this.venueId}})
1 - форматирование
2 - кривое название роута (масло масляное) слово watch тут вообще не подходит, а правильным будет reviewPreview

2023-02-13 10:05 UTC, jurgens commented on src/components/forms/formReview.vue
> +      this.$router.push({name: "previewWatch", params: { id: this.venueId}})
ага, вот теперь вижу куда делась id ресторана
то есть ты ее не потерял, а передаешь через роуты
но во-первых это не надежно, а во-вторых это противоречит заданию, там прописан желаемый URL

2023-02-13 10:05 UTC, jurgens commented on src/components/lists/listReview.vue
> +<template>
снова претензия к названию фолдера
это должно быть components/venues/ReviewList.vue (название сущности идет на первом месте)

2023-02-13 10:05 UTC, jurgens commented on src/components/lists/listReview.vue
> +      <li v-for="(review, index) of review" :key="index">
пропс должен быть во множественном числе - reviews

2023-02-13 10:05 UTC, jurgens commented on src/pages/previewWatch/index.vue
> +      const venueId = +this.$route.params.id
повторю - в данном случае передача venueId через роуты - плохое решение

2023-02-13 10:05 UTC, jurgens commented on src/pages/previewWatch/index.vue
> +</script>
вот гитхаб подсказывает - должна быть пустая строка в конце

2023-02-13 10:05 UTC, jurgens commented on src/pages/thank/index.vue
> +<template>
странное название thank/index - pages/reviewSubmitThankyou.vue

2023-02-13 10:05 UTC, jurgens commented on src/router/index.js
> +  { path: '/previewWatch', name: 'previewWatch', component: previewWatch },
в задании было упомянуто как этот URL должен выглядеть

2023-02-13 10:05 UTC, jurgens commented on src/pages/venues/index.vue
> +    <h1>List restorants</h1>
слово restorants тут быть не должно, сущность называется venues и не надо ничего нового выдумывать

2023-02-13 10:05 UTC, jurgens commented on src/store/review.js
> +    const venueReview = venue.review ? venue.review : [];
вот тут совсем плохо
1 - зачем сохранять review в venue? 
2 - название атрибута review, хотя это должно быть reviews, чтобы понятно было что это массив

2023-02-13 10:05 UTC, jurgens commented on src/store/review.js
> +    const venueReview = venue.review ? venue.review : [];
более правильным решением было бы сохранение в отдельную структуру и независимая работа с ней
через геттер типа getVenueReviews(venueId)

2023-02-14 02:10 UTC, voutanon commented on src/components/forms/formReview.vue
> +<template>
Доволі цікавий підхід, буду однозначно його використовувати в подальшому

2023-02-14 02:13 UTC, voutanon commented on src/store/review.js
> +    const venueReview = venue.review ? venue.review : [];
Тепер обдумавши, як би це було реалізовано на за допомогою ендпоінтів апі розумію, що краще нова структура для цього

2023-05-10 10:53 UTC, closed without merging